import './globals.css'
import type { Metadata } from 'next'
import inter from 'next/font'
import Nav from '@/components/Nav'
import Provider from '@/components/Provider'

export const metadata: Metadata = {
  title: 'PROMPT APP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body >
      <Provider >

      <div className='main'>
         <div className='gradient' />
       </div>

       <main className='app'>
         <Nav />
         {children}
       </main>
      </Provider>
       </body>
    </html>
  )
}
